sources:
  - Sources
templates:
  - ../Sourcery/Templates/Templates
output: Tests/ABSmartlyTests/Mocks/SourceryGenerated.swift
args:
  autoMockableTestableImports: ["ABSmartly"]
  autoMockableImports: ["PromiseKit"]
